services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container_naokihori
    image: naokihori
    ports:
      - "5173:5173"
    volumes:
      - .:/project/src
